/*! See .s */
#ifndef __TEST_H__
#define __TEST_H__

/*! See .s */
void *lidt_and_sti(void *idtr);

#define INTR_V_N_HANDLER_FUNC_NAME(vn) intr_v##vn##_handler

#define INTR_V_N_HANDLER_FUNC(vn) void INTR_V_N_HANDLER_FUNC_NAME(vn)(void)

void init_pics(void);

/*! See .s */
INTR_V_N_HANDLER_FUNC(0);
INTR_V_N_HANDLER_FUNC(1);
INTR_V_N_HANDLER_FUNC(2);
INTR_V_N_HANDLER_FUNC(3);
INTR_V_N_HANDLER_FUNC(4);
INTR_V_N_HANDLER_FUNC(5);
INTR_V_N_HANDLER_FUNC(6);
INTR_V_N_HANDLER_FUNC(7);
INTR_V_N_HANDLER_FUNC(8);
INTR_V_N_HANDLER_FUNC(9);
INTR_V_N_HANDLER_FUNC(10);
INTR_V_N_HANDLER_FUNC(11);
INTR_V_N_HANDLER_FUNC(12);
INTR_V_N_HANDLER_FUNC(13);
INTR_V_N_HANDLER_FUNC(14);
// 15 - RESERVED
INTR_V_N_HANDLER_FUNC(16);
INTR_V_N_HANDLER_FUNC(17);
INTR_V_N_HANDLER_FUNC(18);
INTR_V_N_HANDLER_FUNC(19);
INTR_V_N_HANDLER_FUNC(20);
INTR_V_N_HANDLER_FUNC(21);
// 22 - 31 - RESERVED
INTR_V_N_HANDLER_FUNC(32);
INTR_V_N_HANDLER_FUNC(33);

#endif